defaults:
  - data_loading: data_loading
  - model: rnn
  - training: training
  - logging: logging
  - inference: inference
  - convert: convert
  - environment: environment

hydra:
  run:
    dir: ${hydra:runtime.cwd}/plots/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: .hydra
